// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 neramc

namespace Lightning.Deploy.Core;

using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// The per-target/arch/channel <c>latest.json</c> the updater polls
/// (CLAUDE.md §6.10). Generated by scripts/gen-latest-json.mjs in CI.
/// </summary>
public sealed record UpdateManifest
{
    [JsonPropertyName("version")]
    public required string Version { get; init; }

    [JsonPropertyName("channel")]
    public required string Channel { get; init; }

    [JsonPropertyName("pub_date")]
    public required DateTimeOffset PublishedAt { get; init; }

    [JsonPropertyName("url")]
    public required Uri DownloadUrl { get; init; }

    [JsonPropertyName("sha256")]
    public required string Sha256 { get; init; }

    [JsonPropertyName("signature")]
    public string? Signature { get; init; }

    [JsonPropertyName("notes")]
    public string? Notes { get; init; }

    public static UpdateManifest FromJson(string json) =>
        JsonSerializer.Deserialize<UpdateManifest>(json)
        ?? throw new InvalidDataException("update manifest is empty");

    /// <summary>
    /// Downgrades are rejected — version monotonicity (CLAUDE.md §6.10).
    /// SemVer with an optional prerelease tag; a prerelease is older than
    /// its release.
    /// </summary>
    public bool IsNewerThan(string installedVersion) =>
        CompareSemVer(Version, installedVersion) > 0;

    internal static int CompareSemVer(string left, string right)
    {
        var (leftCore, leftPre) = SplitPrerelease(left);
        var (rightCore, rightPre) = SplitPrerelease(right);

        var coreCompare = new Version(leftCore).CompareTo(new Version(rightCore));
        if (coreCompare != 0)
        {
            return coreCompare;
        }

        // Equal cores: no prerelease > prerelease; otherwise ordinal compare.
        return (leftPre, rightPre) switch
        {
            (null, null) => 0,
            (null, _) => 1,
            (_, null) => -1,
            _ => string.CompareOrdinal(leftPre, rightPre),
        };
    }

    private static (string Core, string? Prerelease) SplitPrerelease(string version)
    {
        var dash = version.IndexOf('-');
        return dash < 0 ? (version, null) : (version[..dash], version[(dash + 1)..]);
    }
}
