// @generated by `pnpm bindings` (crates/ipc-types/src/bin/export_bindings.rs)
// DO NOT EDIT — regenerate after touching any Rust command/event/type (CLAUDE.md §2.4).
// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 neramc

import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';

// This file has been generated by Specta. DO NOT EDIT.

/**
 * One catalog entry — everything the editor renders, as data (§6.5).
 */
export type ActionDefDto = { 
/**
 * Action id.
 */
id: string; 
/**
 * Category id (gradient token + i18n segment).
 */
category: string; 
/**
 * Icon token.
 */
icon: string; 
/**
 * Param schema.
 */
params: ParamDefDto[]; 
/**
 * Output kind id, `null` when dynamic.
 */
output: string | null; 
/**
 * Support matrix.
 */
supports: PlatformSupportDto; 
/**
 * Permission class id, if any.
 */
permission: string | null; 
/**
 * Required runtime capability id, if any.
 */
requiresCapability: string | null; 
/**
 * Param holding reviewable script text, if any.
 */
scriptParam: string | null }

/**
 * Mirror of `lightning_core::Branch`.
 */
export type BranchDto = { 
/**
 * Branch label (`then` / `otherwise` / `body` / menu option).
 */
label: string; 
/**
 * Child steps.
 */
steps: StepDto[] }

/**
 * The runtime capability snapshot (payload of `capability://changed`).
 */
export type CapabilitySnapshotDto = { 
/**
 * OS id (`windows` · `macos` · `linux` · `freebsd`).
 */
os: string; 
/**
 * Environment refinement (e.g. `Wayland`).
 */
environment: string | null; 
/**
 * The `{{os}}` label for `action.unsupportedOnOs` (§8.1).
 */
osLabel: string; 
/**
 * Probed constraints.
 */
capabilities: CapabilityStatusDto[] }

/**
 * One probed capability.
 */
export type CapabilityStatusDto = { 
/**
 * Capability id.
 */
capability: string; 
/**
 * `available` · `degraded` · `unavailable`.
 */
status: string; 
/**
 * Technical reason for degraded/unavailable.
 */
reason: string | null; 
/**
 * "Fix it": tool to install.
 */
fixTool: string | null; 
/**
 * "Fix it": install hint.
 */
fixHint: string | null; 
/**
 * "Fix it": OS permission to grant.
 */
fixPermission: string | null }

/**
 * Typed content value crossing the IPC boundary (mirror of
 * `lightning_core::Content`; dates and paths travel as strings).
 */
export type ContentDto = { type: "nothing" } | { type: "text"; value: string } | { type: "number"; value: number } | { type: "boolean"; value: boolean } | { type: "date"; value: string } | { type: "list"; value: ContentDto[] } | { type: "dictionary"; value: Partial<{ [key in string]: ContentDto }> } | { type: "file"; value: string } | { type: "image"; value: string } | { type: "url"; value: string } | { type: "richText"; value: { html: string; plain: string } } | { type: "error"; value: { message: string } }

/**
 * Mirror of `lightning_core::ErrorPolicy`.
 */
export type ErrorPolicyDto = { policy: "stop" } | { policy: "continue" } | { policy: "retry"; attempts: number; backoff_ms: number }

/**
 * Mirror of `lightning_core::Icon`.
 */
export type IconDto = { 
/**
 * Tile glyph.
 */
glyph: string; 
/**
 * Gradient token (design-system id, never a hex value).
 */
gradient: string }

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

/**
 * One parameter schema entry.
 */
export type ParamDefDto = { 
/**
 * Param key (i18n: `actions.<id>.params.<key>`).
 */
key: string; 
/**
 * `text` · `number` · `boolean` · `date` · `file` · `enum`.
 */
kind: string; 
/**
 * Options when `kind == "enum"`.
 */
options: string[] | null; 
/**
 * Whether required.
 */
required: boolean }

/**
 * Mirror of `lightning_core::ParamValue`.
 */
export type ParamValueDto = { kind: "literal"; value: ContentDto } | { kind: "variable"; name: string } | { kind: "magicOutput"; step: string } | { kind: "template"; template: string }

/**
 * Per-OS support matrix.
 */
export type PlatformSupportDto = { windows: SupportLevelDto; macos: SupportLevelDto; linux: SupportLevelDto; freebsd: SupportLevelDto }

/**
 * One user-visible run log line.
 */
export type RunLogEntryDto = { 
/**
 * RFC3339 timestamp.
 */
at: string; 
/**
 * Step uuid, if step-scoped.
 */
step: string | null; 
/**
 * `info` · `warn` · `error`.
 */
level: string; 
/**
 * Message.
 */
message: string }

/**
 * One `run://progress` event.
 */
export type RunProgressDto = { 
/**
 * Run id.
 */
runId: string; 
/**
 * Step uuid.
 */
step: string; 
/**
 * Action id (drives the block animation without a lookup).
 */
actionId: string; 
/**
 * `started` · `finished` · `failed` · `skipped`.
 */
phase: string; 
/**
 * Output preview for `finished`.
 */
preview: string | null; 
/**
 * Error message for `failed` / `skipped`.
 */
message: string | null }

/**
 * One run-history row.
 */
export type RunRecordDto = { 
/**
 * Shortcut id.
 */
shortcutId: string; 
/**
 * RFC3339 start time.
 */
startedAt: string; 
/**
 * Duration in milliseconds.
 */
durationMs: number; 
/**
 * `success` · `error` · `cancelled`.
 */
status: string; 
/**
 * Error message when failed.
 */
error: string | null }

/**
 * Result of a completed (or failed) run.
 */
export type RunResultDto = { 
/**
 * Run id.
 */
runId: string; 
/**
 * `success` · `error` · `cancelled`.
 */
status: string; 
/**
 * Final output.
 */
output: ContentDto; 
/**
 * Error message when failed.
 */
error: string | null; 
/**
 * The collected run log.
 */
log: RunLogEntryDto[] }

/**
 * Full shortcut document crossing the boundary (editor load/save).
 */
export type ShortcutDto = { 
/**
 * Schema version.
 */
schemaVersion: number; 
/**
 * Shortcut id.
 */
id: string; 
/**
 * Display name.
 */
name: string; 
/**
 * Description.
 */
description: string; 
/**
 * Tile icon.
 */
icon: IconDto; 
/**
 * Global hotkey.
 */
hotkey: string | null; 
/**
 * The flow.
 */
steps: StepDto[]; 
/**
 * Automation trigger block.
 */
trigger: TriggerConfigDto | null }

/**
 * Indexed shortcut metadata (grid tiles, palette).
 */
export type ShortcutMetaDto = { 
/**
 * Shortcut id.
 */
id: string; 
/**
 * Display name.
 */
name: string; 
/**
 * Tile glyph.
 */
iconGlyph: string; 
/**
 * Gradient token.
 */
gradient: string; 
/**
 * Hotkey, if assigned.
 */
hotkey: string | null; 
/**
 * Whether it is an automation.
 */
isAutomation: boolean }

/**
 * Mirror of `lightning_core::Step`.
 */
export type StepDto = { 
/**
 * Step uuid (magic-variable identity).
 */
uuid: string; 
/**
 * Action id.
 */
actionId: string; 
/**
 * Parameter values.
 */
params: Partial<{ [key in string]: ParamValueDto }>; 
/**
 * Error policy.
 */
errorPolicy: ErrorPolicyDto; 
/**
 * Control-flow children.
 */
branches: BranchDto[] }

/**
 * One support level.
 */
export type SupportLevelDto = { 
/**
 * `full` · `partial` · `none`.
 */
level: string; 
/**
 * Note for `partial`.
 */
note: string | null }

/**
 * Mirror of `lightning_core::TriggerConfig`.
 */
export type TriggerConfigDto = { 
/**
 * Trigger id.
 */
triggerId: string; 
/**
 * Trigger-specific config JSON.
 */
config: JsonValue; 
/**
 * Whether the automation is armed.
 */
enabled: boolean; 
/**
 * Cooldown override in milliseconds.
 */
cooldownMs: number | null }


export async function listActions(): Promise<ActionDefDto[]> {
  return await invoke<ActionDefDto[]>('list_actions');
}

export async function getCapabilities(): Promise<CapabilitySnapshotDto> {
  return await invoke<CapabilitySnapshotDto>('get_capabilities');
}

export async function listShortcuts(): Promise<ShortcutMetaDto[]> {
  return await invoke<ShortcutMetaDto[]>('list_shortcuts');
}

export async function loadShortcut(id: string): Promise<ShortcutDto> {
  return await invoke<ShortcutDto>('load_shortcut', { id });
}

export async function saveShortcut(shortcut: ShortcutDto): Promise<ShortcutMetaDto> {
  return await invoke<ShortcutMetaDto>('save_shortcut', { shortcut });
}

export async function deleteShortcut(id: string): Promise<null> {
  return await invoke<null>('delete_shortcut', { id });
}

export async function runShortcut(id: string): Promise<RunResultDto> {
  return await invoke<RunResultDto>('run_shortcut', { id });
}

export async function cancelRun(runId: string): Promise<null> {
  return await invoke<null>('cancel_run', { runId });
}

export async function listRecentRuns(id: string, limit: number): Promise<RunRecordDto[]> {
  return await invoke<RunRecordDto[]>('list_recent_runs', { id, limit });
}

export const EVENTS = {
  runProgress: 'run://progress',
  triggersFired: 'triggers://fired',
  capabilityChanged: 'capability://changed',
  storeChanged: 'store://changed',
} as const;

export function onRunProgress(
  handler: (payload: RunProgressDto) => void,
): Promise<UnlistenFn> {
  return listen<RunProgressDto>(EVENTS.runProgress, (event) => handler(event.payload));
}

export function onCapabilityChanged(
  handler: (payload: CapabilitySnapshotDto) => void,
): Promise<UnlistenFn> {
  return listen<CapabilitySnapshotDto>(EVENTS.capabilityChanged, (event) =>
    handler(event.payload),
  );
}

export function onStoreChanged(handler: (shortcutId: string) => void): Promise<UnlistenFn> {
  return listen<string>(EVENTS.storeChanged, (event) => handler(event.payload));
}
